// Conteúdo do Manual do Usuário incorporado diretamente no bundle.
// Para atualizar o manual, edite o array abaixo.

export const manualContent = [
   "# Manual do Usuário TymerBook",
   "",
   "## 1. Bem-vindo ao TymerBook!",
   "",
   "### A Plataforma Definitiva para Gestão e Agendamentos de Barbearias",
   "",
   "O TymerBook é muito mais que um simples sistema de agendamento. É uma solução completa projetada especificamente para donos de barbearias que desejam modernizar seu negócio, economizar tempo e aumentar o faturamento.",
   "",
   "### Principais Benefícios:",
   "",
      "- ✅ **Mais Agendamentos**: Página pública de agendamento disponível 24/7, permitindo que clientes agendem a qualquer hora",
      "- ✅ **Menos Faltas (No-Shows)**: Sistema inteligente de lembretes automáticos via WhatsApp reduz drasticamente as faltas",
      "- ✅ **Gestão Financeira Simplificada**: Relatórios detalhados e controle completo do faturamento",
      "- ✅ **Comunicação Profissional**: Automação de mensagens de confirmação e lembretes personalizados",
      "- ✅ **Dashboard Intuitivo**: Visualização completa do seu negócio em tempo real",
      "- ✅ **Reativação de Clientes**: Ferramenta para identificar e reengajar clientes inativos",
   "",
   "---",
   "",
   "## 2. Primeiros Passos: Configurando sua Barbearia em Minutos",
   "",
   "### 2.1 Contratação do Serviço",
   "",
   "1. **Escolha seu Plano**: Acesse [l.tymerbook.com](https://l.tymerbook.com) e escolha entre:",
   "   - **Básico**: Até 1 profissional",
   "   - **Premium**: Até 3 profissionais",
   "   - **Ultra**: Profissionais ilimitados",
   "",
   "2. **Checkout Seguro**: Você será redirecionado para nossa plataforma de pagamento segura (Kirvano)",
   "",
   "3. **Conta Automática**: Após o pagamento aprovado, sua conta é criada automaticamente",
   "",
   "### 2.2 Primeiro Login",
   "",
   "1. **E-mail de Boas-vindas**: Você receberá um e-mail com suas credenciais de acesso:",
   "   - E-mail de login",
   "   - Senha temporária",
   "",
   "2. **Acesso ao Sistema**: Entre em [www.tymerbook.com/login](https://www.tymerbook.com/login) com suas credenciais",
   "",
   "### 2.3 Configurações Iniciais Essenciais",
   "",
   "**IMPORTANTE**: Antes de usar o sistema, configure estas informações na seção **Configurações > Estabelecimento**:",
   "",
   "#### Informações do Estabelecimento:",
   "- **Nome do Estabelecimento**: Como sua barbearia aparecerá para os clientes",
   "- **E-mail**: E-mail principal do negócio",
   "- **Telefone**: Número de contato (formato: (11) 99999-9999)",
   "- **Endereço**: Localização completa do estabelecimento",
   "- **Instagram**: URL ou @ do seu perfil no Instagram (opcional)",
   "- **Upload do Logo**: Imagem que representará sua marca",
   "",
   "#### Link Personalizado (ESSENCIAL):",
   "- **Campo obrigatório**: Define sua URL pública de agendamento",
   "- **Formato**: Exemplo: `barbearia-do-ze`",
   "- **Resultado**: Sua página será `tymerbook.com/agendamento/barbearia-do-ze`",
   "- **Importante**: Não use espaços ou caracteres especiais, apenas o hífen (-)",
   "",
   "> 💡 **Dica**: Escolha um link fácil de lembrar e que represente sua marca. Este será o endereço que seus clientes usarão para agendar!",
   "",
   "#### Próximos Passos Obrigatórios:",
   "",
   "Após configurar as informações básicas, você deve completar estas configurações essenciais:",
   "",
   "**1. Cadastrar Profissionais:**",
   "- Acesse **Configurações > Profissionais**",
   "- Adicione todos os membros da sua equipe",
   "- Configure nome, especialidade e foto de cada um",
   "",
   "**2. Cadastrar Serviços:**",
   "- Acesse **Configurações > Serviços**",
   "- Adicione todos os serviços oferecidos (corte, barba, etc.)",
   "- Defina preço e duração para cada serviço. Adicione também foto de cada serviço",
   "",
   "**3. Configurar Horários (IMPORTANTE):**",
   "- **Primeiro**: Configure o horário geral do estabelecimento em **Configurações > Horários**",
   "- **Depois**: Configure os horários individuais de cada profissional na mesma seção",
   "- **Atenção**: Os dois estão interligados - o horário do profissional deve estar dentro do horário do estabelecimento",
   "- Sem essas configurações, os clientes não conseguirão agendar online",
   "",
   "> ⚠️ **Importante**: Estas configurações são obrigatórias para que o sistema funcione corretamente. Sem profissionais, serviços e horários configurados, sua página pública de agendamento não estará disponível para os clientes.",
   "",
   "---",
   "",
   "## 3. Funcionalidades Detalhadas (O Coração do Seu Negócio)",
   "",
   "### 3.1 Dashboard - Sua Central de Comando",
   "",
   "O Dashboard é a primeira tela que você vê ao entrar no sistema e oferece uma visão completa do seu negócio:",
   "",
   "#### Cards de Estatísticas:",
   "- **Faturamento Hoje**: Receita do dia atual em tempo real",
   "- **Clientes Ativos**: Total de clientes cadastrados no sistema",
   "- **Agendamentos Hoje**: Quantidade de agendamentos para o dia",
   "- **Taxa de Ocupação**: Percentual de horários ocupados vs disponíveis",
   "",
   "#### Seções Interativas:",
   "",
   "**\"Próximos na Fila\":**",
   "- Mostra os próximos agendamentos do dia",
   "- Status em tempo real (Confirmado, Concluído, Cancelado)",
   "- Informações do cliente, serviço e horário",
   "",
   "**\"Agenda de Hoje\":**",
   "- Visão detalhada dos agendamentos do dia",
   "- Opção para marcar como concluído",
   "- Botão para criar novo agendamento",
   "",
   "**\"Ocupação por Profissional\":**",
   "- Gráfico visual da agenda de cada profissional",
   "- Identificação rápida de horários livres",
   "- Produtividade individual",
   "",
   "**\"Ações Rápidas\":**",
   "- Novo Cliente: Acesso direto ao cadastro",
   "- Agendar: Criação rápida de agendamento",
   "- Relatórios: Acesso aos dados financeiros",
   "- Configurações: Ajustes do sistema",
   "",
   "### 3.2 Agenda - Gerenciamento de Agendamentos",
   "",
   "#### Visualização da Agenda:",
   "- **Visão Diária**: Todos os horários do dia por profissional",
   "- **Status Visual**: Cores diferentes para cada status (confirmado, concluído, cancelado)",
   "- **Filtros**: Por profissional, data ou status",
   "",
   "#### Criar Novo Agendamento:",
   "1. **Selecionar Cliente**: Busque por nome ou telefone, ou cadastre novo cliente",
   "2. **Escolher Serviço**: Lista de serviços cadastrados com preços e duração",
   "3. **Definir Profissional**: Escolha o profissional ou deixe \"Qualquer um\"",
   "4. **Data e Horário**: Seleção em calendário com horários disponíveis",
   "5. **Observações**: Campo opcional para informações extras",
   "",
   "#### Gerenciar Agendamentos Existentes:",
   "- **Editar**: Alterar data, horário ou serviços",
   "- **Cancelar**: Com opção de informar motivo",
   "- **Concluir**: Marcar como finalizado",
   "- **Pagamento**: Registrar forma de pagamento",
   "",
   "### 3.3 Clientes - Base de Dados Inteligente",
   "",
   "#### Cadastro de Clientes:",
   "- **Informações Básicas**: Nome, telefone, e-mail",
   "- **Data de Nascimento**: Para campanhas de aniversário",
   "- **Observações**: Preferências ou informações importantes",
   "",
   "#### Histórico Completo:",
   "- **Total de Agendamentos**: Quantas vezes o cliente visitou",
   "- **Valor Gasto**: Soma de todos os gastos no estabelecimento",
   "- **Última Visita**: Data do último agendamento",
   "- **Serviços Favoritos**: Análise dos serviços mais utilizados",
   "",
   "#### Clientes Inativos:",
   "- **Identificação Automática**: Sistema detecta clientes sem visitas recentes",
   "- **Filtros por Período**: 15, 30, 60 ou 90 dias sem visitar",
   "- **Receita Potencial**: Cálculo do valor que poderiam gastar",
   "- **Campanha de Reativação**: Envio de promoções via WhatsApp",
   "",
   "### 3.4 WhatsApp - Automações Inteligentes",
   "",
   "O sistema de WhatsApp é um dos grandes diferenciais do TymerBook, reduzindo drasticamente as faltas e melhorando a comunicação com clientes.",
   "",
   "#### 3.4.1 Conexão do WhatsApp",
   "",
   "**Passo a Passo para Conectar:**",
   "",
   "1. **Acessar Configurações**: Vá em Dashboard > WhatsApp",
   "2. **Clicar em \"Conectar\"**: Botão para iniciar o processo",
   "3. **Escanear QR Code**: Use a câmera do WhatsApp Business do seu celular",
   "4. **Confirmação**: Sistema confirmará a conexão em alguns segundos",
   "",
   "**Requisitos:**",
   "- WhatsApp Business instalado no seu celular",
   "- Número do estabelecimento (não pode ser número pessoal)",
   "- Conexão estável com internet",
   "",
   "#### 3.4.2 Automações Disponíveis",
   "",
   "**Confirmação de Agendamento:**",
   "- **Quando**: Enviado imediatamente após cliente agendar",
   "- **Conteúdo**: Detalhes do agendamento (data, hora, serviço, profissional, valor)",
   "- **Objetivo**: Confirmar que o agendamento foi recebido",
   "",
   "**Lembrete 24 horas:**",
   "- **Quando**: 24 horas antes do agendamento",
   "- **Conteúdo**: Lembrete amigável com detalhes do agendamento",
   "- **Objetivo**: Reduzir faltas e dar tempo para reagendamento se necessário",
   "",
   "**Lembrete 12 horas:**",
   "- **Quando**: 12 horas antes do agendamento",
   "- **Conteúdo**: Lembrete mais próximo com orientações",
   "- **Objetivo**: Garantir que o cliente não esqueça",
   "",
   "**Lembrete 2 horas:**",
   "- **Quando**: 2 horas antes do agendamento",
   "- **Conteúdo**: Lembrete final com orientação para chegar 10 min antes",
   "- **Objetivo**: Confirmação final e pontualidade",
   "",
   "#### 3.4.3 Configuração das Automações",
   "",
   "**Para Ativar/Desativar Automações:**",
   "1. Acesse Dashboard > WhatsApp",
   "2. Localize a seção \"Configurações de Automação\"",
   "3. Use os interruptores para ativar/desativar cada tipo de mensagem",
   "4. As alterações são salvas automaticamente",
   "",
   "**Testar Mensagem:**",
   "- **Ferramenta de Teste**: Envie uma mensagem de teste para qualquer número",
   "- **Templates Prontos**: Modelos de confirmação e lembretes para testar",
   "- **Verificação**: Confirme se a integração está funcionando corretamente",
   "",
   "#### 3.4.4 Mensagens de Reativação",
   "",
   "**Para Clientes Inativos:**",
   "- Acesse Dashboard > Clientes Inativos",
   "- Selecione os clientes desejados",
   "- Escolha um template de promoção",
   "- Envie mensagens personalizadas em massa",
   "",
   "### 3.5 Configurações - Personalizando sua Barbearia",
   "",
   "#### 3.5.1 Profissionais",
   "",
   "**Cadastrar Equipe:**",
   "- **Nome Completo**: Identificação do profissional",
   "- **E-mail**: Para notificações (opcional)",
   "- **Telefone**: Contato direto",
   "- **Especialidade**: Ex: Corte masculino, Barba, Sobrancelha",
   "- **Upload de Foto**: Avatar para identificação visual",
   "",
   "**Sistema de Horários Individuais:**",
   "",
   "**Dias de Trabalho:**",
   "- Configure quais dias da semana cada profissional trabalha",
   "- Flexibilidade total para escalas diferentes",
   "",
   "**Horários de Início/Fim:**",
   "- Defina horário de entrada e saída para cada dia",
   "- Permite horários diferentes para cada dia da semana",
   "",
   "**Intervalos Recorrentes:**",
   "- Configure intervalos fixos (ex: almoço das 12h às 13h)",
   "- Automaticamente bloqueados na agenda",
   "",
   "**Exceções Pontuais:**",
   "- Bloqueie dias específicos (férias, folgas, compromissos)",
   "- Horários especiais para datas específicas",
   "- Fácil gestão de ausências",
   "",
   "#### 3.5.2 Serviços",
   "",
   "**Cadastro Completo:**",
   "- **Nome do Serviço**: Ex: Corte Masculino, Barba, Sobrancelha",
   "- **Descrição**: Detalhes do que está incluído",
   "- **Preço**: Valor em reais",
   "- **Duração**: Tempo necessário em minutos",
   "- **Upload de Imagem**: Foto representativa do serviço",
   "",
   "**Gestão de Preços:**",
   "- Atualização fácil de valores",
   "- Histórico de alterações",
   "- Diferentes preços por profissional (se necessário)",
   "",
   "#### 3.5.3 Promoções",
   "",
   "**Templates de Mensagem:**",
   "- **Modelos Prontos**: Para diferentes tipos de promoção",
   "- **Personalização**: Adapte as mensagens à sua marca",
   "- **Variáveis Dinâmicas**: Nome do cliente, link de agendamento automático",
   "",
   "**Exemplos de Templates:**",
   "- Desconto de aniversário",
   "- Promoção de retorno",
   "- Ofertas sazonais",
   "- Pacotes especiais",
   "",
   "---",
   "",
   "## 4. Sua Página Pública de Agendamento",
   "",
   "### 4.1 Como Funciona para o Cliente Final",
   "",
   "Seu link personalizado (`tymerbook.com/agendamento/[seu-link]`) oferece uma experiência completa de agendamento:",
   "",
   "#### Fluxo do Cliente:",
   "",
   "**Etapa 1 - Escolher Serviço:**",
   "- Lista visual de todos os serviços disponíveis",
   "- Preços e durações claramente exibidos",
   "- Imagens dos serviços (se cadastradas)",
   "- Opção de adicionar serviços complementares",
   "",
   "**Etapa 2 - Selecionar Profissional:**",
   "- Fotos e especialidades dos profissionais",
   "- Opção \"Qualquer profissional\" disponível",
   "- Horários específicos de cada um",
   "",
   "**Etapa 3 - Escolher Data:**",
   "- Calendário interativo",
   "- Apenas datas disponíveis aparecem",
   "- Bloqueios automáticos de feriados/folgas",
   "",
   "**Etapa 4 - Selecionar Horário:**",
   "- Grade de horários disponíveis",
   "- Atualização em tempo real",
   "- Duração total calculada automaticamente",
   "",
   "**Etapa 5 - Dados do Cliente:**",
   "- Formulário simples e intuitivo",
   "- Campos: Nome, telefone, e-mail",
   "- Data de nascimento (opcional)",
   "- Observações (opcional)",
   "",
   "**Etapa 6 - Confirmação:**",
   "- Resumo completo do agendamento",
   "- Valor total e forma de pagamento",
   "- Confirmação via WhatsApp automática",
   "",
   "### 4.2 QR Code para Impressão",
   "",
   "#### Gerar QR Code:",
   "1. **Acesso**: Configurações > Estabelecimento",
   "2. **Localizar**: Seção \"Link Público do Agendamento\"",
   "3. **Clicar**: \"Gerar QR Code para Impressão\"",
   "",
   "#### Funcionalidades do QR Code:",
   "- **Preview do Cartaz**: Visualize antes de imprimir",
   "- **Logo Personalizado**: Sua marca no cartaz",
   "- **Download em PDF**: Arquivo pronto para impressão",
   "- **Tamanho Otimizado**: Ideal para colar no estabelecimento",
   "",
   "#### Como Usar:",
   "- Imprima o PDF gerado",
   "- Cole em local visível na barbearia (balcão, parede, espelho)",
   "- Clientes escaneiam com a câmera do celular",
   "- Redirecionamento automático para sua página de agendamento",
   "- Facilita o agendamento dos clientes que aparecem no estabelecimento sem horário agendado",
   "- Melhora na gestão, pois previne esquecimento de agendamentos pelo profissional",
   "",
   "---",
   "",
   "## 5. Gerenciamento da Sua Assinatura",
   "",
   "### 5.1 Página de Assinatura",
   "",
   "Acesse **Dashboard > Minha Assinatura** para visualizar:",
   "",
   "#### Informações da Conta:",
   "- **Plano Atual**: Básico, Premium ou Ultra",
   "- **Status**: Ativa, Atrasada ou Cancelada",
   "- **Data de Renovação**: Próximo vencimento",
   "- **Ciclo de Pagamento**: Mensal ou Anual",
   "",
   "#### Recursos Inclusos:",
   "**Básico:**",
   "- Até 1 profissional",
   "- Clientes ilimitados",
   "- Agendamentos ilimitados",
   "- Serviços ilimitados",
   "- Integração WhatsApp",
   "",
   "**Premium:**",
   "- Até 3 profissionais",
   "- Todos os recursos do Básico",
   "- Relatórios avançados",
   "",
   "**Ultra:**",
   "- Profissionais ilimitados",
   "- Todos os recursos do Premium",
   "- Suporte prioritário",
   "",
   "### 5.2 Limites de Plano",
   "",
   "#### Sistema de Controle:",
   "- **Contagem Automática**: Sistema monitora uso em tempo real",
   "- **Alertas Visuais**: Notificação quando próximo do limite",
   "- **Bloqueio Preventivo**: Impede criação além do limite",
   "- **Sugestões de Upgrade**: Orientações para expandir",
   "",
   "#### Para Profissionais:",
   "- **Básico**: Máximo 1 profissional ativo",
   "- **Premium**: Máximo 3 profissionais ativos",
   "- **Ultra**: Ilimitado",
   "",
   "### 5.3 Portal da Kirvano",
   "",
   "#### Gerenciar Assinatura:",
   "1. **Clicar**: \"Gerenciar Assinatura\" na página de assinatura",
   "2. **Redirecionamento**: Portal seguro da Kirvano",
   "3. **Funcionalidades Disponíveis**:",
   "   - Atualizar cartão de crédito",
   "   - Alterar dados de cobrança",
   "   - Cancelar assinatura",
   "   - Histórico de pagamentos",
   "   - Alterar plano",
   "",
   "#### Segurança:",
   "- Portal criptografado e seguro",
   "- Dados de pagamento protegidos",
   "- Retorno automático ao TymerBook",
   "- Notificações por e-mail",
   "",
   "---",
   "",
   "## 6. Disponibilidade e Suporte",
   "",
   "### 6.1 Infraestrutura de Alta Performance",
   "",
   "#### Disponibilidade 24/7:",
   "- **Servidor VPS Dedicado**: Hospedagem em servidor de alta performance",
   "- **Uptime 99.9%**: Sistema disponível 24 horas por dia, 7 dias por semana",
   "- **Monitoramento Contínuo**: Equipe técnica monitora o sistema constantemente",
   "- **Redundância**: Múltiplos pontos de acesso para garantir disponibilidade",
   "",
   "#### Segurança dos Dados:",
   "- **Backups Automáticos**: Realizados diariamente",
   "- **Criptografia**: Dados protegidos com tecnologia SSL",
   "- **Conformidade LGPD**: Tratamento seguro de dados pessoais",
   "- **Armazenamento Seguro**: Dados em ambiente protegido",
   "",
   "### 6.2 Suporte Técnico",
   "",
   "#### Como Obter Ajuda:",
   "",
   "**Através do Sistema:**",
   "1. Acesse Dashboard > Minha Assinatura",
   "2. Clique em \"Contatar Suporte\"",
   "3. Será redirecionado diretamente para o WhatsApp, onde receberá o devido suporte",
   "4. Nossa equipe responderá o mais rápido possível",
   "",
   "**Tipos de Suporte:**",
   "- **Dúvidas sobre Funcionalidades**: Como usar recursos do sistema",
   "- **Problemas Técnicos**: Dificuldades de acesso ou erro no sistema",
   "- **Configuração Inicial**: Ajuda para primeiros passos",
   "- **Integração WhatsApp**: Suporte para conexão e automações",
   "- **Treinamento**: Orientações para aproveitar melhor o sistema",
   "",
   "#### Canais de Suporte:",
   "- **E-mail**: suporte@tymerbook.com",
   "- **WhatsApp**: Disponível na página de assinatura",
   "",
   "#### Suporte Prioritário (Plano Ultra):",
   "- **Resposta em até 2 horas**: Atendimento mais rápido",
   "- **Canal Direto**: Linha de contato exclusiva",
   "- **Suporte via Telefone**: Quando necessário",
   "- **Treinamento Personalizado**: Sessões individuais quando solicitado",
   "",
   "---",
   "",
   "## 7. Dicas para Maximizar Resultados",
   "",
   "### 7.1 Melhores Práticas",
   "",
   "#### Configure Corretamente:",
   "- ✅ Preencha todas as informações do estabelecimento",
   "- ✅ Cadastre todos os profissionais com fotos",
   "- ✅ Configure horários individuais detalhadamente",
   "- ✅ Adicione imagens aos serviços",
   "- ✅ Conecte o WhatsApp e ative todas as automações",
   "",
   "#### Use as Automações:",
   "- ✅ Mantenha lembretes ativos para reduzir faltas",
   "- ✅ Configure mensagens de reativação",
   "- ✅ Monitore estatísticas de entrega",
   "- ✅ Teste mensagens regularmente",
   "",
   "#### Promova Sua Página:",
   "- ✅ Imprima e cole o QR Code no estabelecimento",
   "- ✅ Compartilhe o link nas redes sociais",
   "- ✅ Inclua o link na assinatura do e-mail",
   "- ✅ Oriente clientes sobre o agendamento online",
   "",
   "### 7.2 Métricas Importantes",
   "",
   "#### Acompanhe Regularmente:",
   "- **Taxa de Ocupação**: Meta acima de 70%",
   "- **No-Show Rate**: Objetivo abaixo de 10%",
   "- **Clientes Inativos**: Reaproveite mensalmente",
   "- **Faturamento Diário**: Compare com períodos anteriores",
   "- **Efetividade WhatsApp**: Taxa de entrega acima de 95%",
   "",
   "#### Relatórios Mensais:",
   "- Analise crescimento de faturamento",
   "- Identifique profissionais mais produtivos",
   "- Verifique evolução da base de clientes",
   "- Acompanhe sazonalidade dos serviços",
   "",
   "---",
   "",
   "## 8. Solução de Problemas Comuns",
   "",
   "### 8.1 WhatsApp não Conecta",
   "",
   "**Possíveis Causas:**",
   "- QR Code expirado",
   "- WhatsApp Business não instalado",
   "- Problemas de conexão",
   "",
   "**Soluções:**",
   "1. Atualize a página e gere novo QR Code",
   "2. Certifique-se de usar WhatsApp Business",
   "3. Verifique conexão com internet",
   "",
   "### 8.2 Agendamentos não Aparecem",
   "",
   "**Verificações:**",
   "- Confirme data e filtros aplicados",
   "- Verifique se profissional está ativo",
   "- Confirme se agendamento não foi cancelado",
   "",
   "### 8.3 Clientes não Conseguem Agendar",
   "",
   "**Possíveis Problemas:**",
   "- Horários não configurados",
   "- Profissional sem agenda ativa",
   "- Serviços inativos",
   "- Link personalizado incorreto",
   "",
   "**Soluções:**",
   "- Revise configurações de horários",
   "- Ative agendas dos profissionais",
   "- Verifique status dos serviços",
   "- Confirme link nas configurações",
   "",
   "---",
   "",
   "## Conclusão",
   "",
   "O TymerBook foi desenvolvido especificamente para transformar a gestão do seu estabelecimento, automatizando processos, reduzindo faltas e aumentando o faturamento. Com este manual, você tem todas as informações necessárias para aproveitar ao máximo todas as funcionalidades.",
   "",
   "### Próximos Passos:",
   "1. ✅ Complete a configuração inicial",
   "2. ✅ Cadastre sua equipe e serviços",
   "3. ✅ Configure os horários",
   "4. ✅ Conecte o WhatsApp e ative automações",
   "5. ✅ Imprima e cole o QR Code",
   "6. ✅ Comece a agendar e acompanhar resultados",
   "",
   "**Lembre-se**: Nossa equipe de suporte está sempre disponível para ajudar você a ter sucesso com o TymerBook!",
   "",
   "---",
   "",
   "*Este manual é atualizado regularmente. Para dúvidas ou sugestões, entre em contato através do botão \"Contatar Suporte\" em sua conta.*",
   "",
   "TymerBook © 2025 – Foco em resultados para sua barbearia.",
].join("\n");