// Conteúdo do Manual do Usuário incorporado diretamente no bundle.
// Para atualizar o manual, edite o array abaixo.

export const manualContent = [
   "# Manual do Usuário TymerBook",
   "",
   "## 1. Bem-vindo ao TymerBook!",
   "",
   "### A Plataforma Definitiva para Gestão e Agendamentos de Barbearias",
   "",
   "O TymerBook é muito mais que um simples sistema de agendamento. É uma solução completa projetada especificamente para donos de barbearias que desejam modernizar seu negócio, economizar tempo e aumentar o faturamento.",
   "",
   "### Principais Benefícios:",
   "",
      "- ✅ **Mais Agendamentos**: Página pública de agendamento disponível 24/7, permitindo que clientes agendem a qualquer hora",
      "- ✅ **Menos Faltas (No-Shows)**: Sistema inteligente de lembretes automáticos via WhatsApp reduz drasticamente as faltas",
      "- ✅ **Gestão Financeira Simplificada**: Relatórios detalhados e controle completo do faturamento",
      "- ✅ **Comunicação Profissional**: Automação de mensagens de confirmação e lembretes personalizados",
      "- ✅ **Dashboard Intuitivo**: Visualização completa do seu negócio em tempo real",
      "- ✅ **Reativação de Clientes**: Ferramenta para identificar e reengajar clientes inativos",
   "",
   "---",
   "",
   "## 2. Primeiros Passos: Configurando sua Barbearia em Minutos",
   "",
   "### 2.1 Contratação do Serviço",
   "",
   "1. **Escolha seu Plano**: Acesse [l.tymerbook.com](https://l.tymerbook.com) e escolha entre:",
   "   - **Básico**: Até 1 profissional",
   "   - **Premium**: Até 3 profissionais",
   "   - **Ultra**: Profissionais ilimitados",
   "",
   "2. **Checkout Seguro**: Você será redirecionado para nossa plataforma de pagamento segura (Kirvano)",
   "",
   "3. **Conta Automática**: Após o pagamento aprovado, sua conta é criada automaticamente",
   "",
   "### 2.2 Primeiro Login",
   "",
   "1. **E-mail de Boas-vindas**: Você receberá um e-mail com suas credenciais de acesso:",
   "   - E-mail de login",
   "   - Senha temporária",
   "",
   "2. **Acesso ao Sistema**: Entre em [www.tymerbook.com/login](https://www.tymerbook.com/login) com suas credenciais",
   "",
   "### 2.3 Configurações Iniciais Essenciais",
   "",
   "**IMPORTANTE**: Antes de usar o sistema, configure estas informações na seção **Configurações > Estabelecimento**:",
   "",
   "#### Informações do Estabelecimento:",
   "- **Nome do Estabelecimento**: Como sua barbearia aparecerá para os clientes",
   "- **E-mail**: E-mail principal do negócio",
   "- **Telefone**: Número de contato (formato: (11) 99999-9999)",
   "- **Endereço**: Localização completa do estabelecimento",
   "- **Instagram**: URL ou @ do seu perfil no Instagram (opcional)",
   "- **Upload do Logo**: Imagem que representará sua marca",
   "",
   "#### Link Personalizado (ESSENCIAL):",
   "- **Campo obrigatório**: Define sua URL pública de agendamento",
   "- **Formato**: Exemplo: `barbearia-do-ze`",
   "- **Resultado**: Sua página será `tymerbook.com/agendamento/barbearia-do-ze`",
   "- **Importante**: Não use espaços ou caracteres especiais, apenas o hífen (-)",
   "",
   "> 💡 **Dica**: Escolha um link fácil de lembrar e que represente sua marca. Este será o endereço que seus clientes usarão para agendar!",
   "",
   "#### Próximos Passos Obrigatórios:",
   "",
   "Após configurar as informações básicas, você deve completar estas configurações essenciais:",
   "",
   "**1. Cadastrar Profissionais:**",
   "- Acesse **Configurações > Profissionais**",
   "- Adicione todos os membros da sua equipe",
   "- Configure nome, especialidade e foto de cada um",
   "",
   "**2. Cadastrar Serviços:**",
   "- Acesse **Configurações > Serviços**",
   "- Adicione todos os serviços oferecidos (corte, barba, etc.)",
   "- Defina preço e duração para cada serviço. Adicione também foto de cada serviço",
   "",
   "**3. Configurar Horários (IMPORTANTE):**",
   "- **Primeiro**: Configure o horário geral do estabelecimento em **Configurações > Horários**",
   "- **Depois**: Configure os horários individuais de cada profissional na mesma seção",
   "- **Atenção**: Os dois estão interligados - o horário do profissional deve estar dentro do horário do estabelecimento",
   "- Sem essas configurações, os clientes não conseguirão agendar online",
   "",
   "> ⚠️ **Importante**: Estas configurações são obrigatórias para que o sistema funcione corretamente. Sem profissionais, serviços e horários configurados, sua página pública de agendamento não estará disponível para os clientes.",
   "",
   "---",
   "",
   "## 3. Funcionalidades Detalhadas (O Coração do Seu Negócio)",
   "",
   "### 3.1 Dashboard - Sua Central de Comando",
   "",
   "O Dashboard é a primeira tela que você vê ao entrar no sistema e oferece uma visão completa do seu negócio:",
   "",
   "#### Cards de Estatísticas:",
   "- **Faturamento Hoje**: Receita do dia atual em tempo real",
   "- **Clientes Ativos**: Total de clientes cadastrados no sistema",
   "- **Agendamentos Hoje**: Quantidade de agendamentos para o dia",
   "- **Taxa de Ocupação**: Percentual de horários ocupados vs disponíveis",
   "",
   "#### Seções Interativas:",
   "",
   "**\"Próximos na Fila\":**",
   "- Mostra os próximos agendamentos do dia",
   "- Status em tempo real (Confirmado, Concluído, Cancelado)",
   "- Informações do cliente, serviço e horário",
   "",
   "**\"Agenda de Hoje\":**",
   "- Visão detalhada dos agendamentos do dia",
   "- Opção para marcar como concluído",
   "- Botão para criar novo agendamento",
   "",
   "**\"Ocupação por Profissional\":**",
   "- Gráfico visual da agenda de cada profissional",
   "- Identificação rápida de horários livres",
   "- Produtividade individual",
   "",
   "**\"Ações Rápidas\":**",
   "- Novo Cliente: Acesso direto ao cadastro",
   "- Agendar: Criação rápida de agendamento",
   "- Relatórios: Acesso aos dados financeiros",
   "- Configurações: Ajustes do sistema",
   "",
   "### 3.2 Agenda - Gerenciamento de Agendamentos",
   "",
   "#### Visualização da Agenda:",
   "- **Visão Diária**: Todos os horários do dia por profissional",
   "- **Status Visual**: Cores diferentes para cada status (confirmado, concluído, cancelado)",
   "- **Filtros**: Por profissional, data ou status",
   "",
   "#### Criar Novo Agendamento:",
   "1. **Selecionar Cliente**: Busque por nome ou telefone, ou cadastre novo cliente",
   "2. **Escolher Serviço**: Lista de serviços cadastrados com preços e duração",
   "3. **Definir Profissional**: Escolha o profissional ou deixe \"Qualquer um\"",
   "4. **Data e Horário**: Seleção em calendário com horários disponíveis",
   "5. **Observações**: Campo opcional para informações extras",
   "",
   "#### Gerenciar Agendamentos Existentes:",
   "- **Editar**: Alterar data, horário ou serviços",
   "- **Cancelar**: Com opção de informar motivo",
   "- **Concluir**: Marcar como finalizado",
   "- **Pagamento**: Registrar forma de pagamento",
   "",
   "### 3.3 Clientes - Base de Dados Inteligente",
   "",
   "#### Cadastro de Clientes:",
   "- **Informações Básicas**: Nome, telefone, e-mail",
   "- **Data de Nascimento**: Para campanhas de aniversário",
   "- **Observações**: Preferências ou informações importantes",
   "",
   "#### Histórico Completo:",
   "- **Total de Agendamentos**: Quantas vezes o cliente visitou",
   "- **Valor Gasto**: Soma de todos os gastos no estabelecimento",
   "- **Última Visita**: Data do último agendamento",
   "- **Serviços Favoritos**: Análise dos serviços mais utilizados",
   "",
   "#### Clientes Inativos:",
   "- **Identificação Automática**: Sistema detecta clientes sem visitas recentes",
   "- **Filtros por Período**: 15, 30, 60 ou 90 dias sem visitar",
   "- **Receita Potencial**: Cálculo do valor que poderiam gastar",
   "- **Campanha de Reativação**: Envio de promoções via WhatsApp",
   "",
   "#### Clientes de Balcão (Novo Fluxo Inteligente):",
   "- **O que são**: Clientes atendidos rapidamente sem registro completo inicial.",
   "- **Armazenamento Limpo**: Por padrão ficam ocultos na listagem principal para não poluir sua base.",
   "- **Como Exibir**: Ative o checkbox 'Incluir clientes de Balcão' na tela de Clientes para visualizá-los.",
   "- **Badge Visual**: Identificados com a tag 'Balcão' na listagem.",
   "- **Reutilização**: Retornos desses clientes podem ser vinculados novamente sem criar duplicados.",
   "",
   "##### Busca Inteligente no Modal de Agendamento:",
   "- Campo 'Buscar Cliente' agora usa busca agrupada em tempo real.",
   "- Resultados são exibidos em dois grupos: 'Clientes Cadastrados' e 'Clientes de Balcão'.",
   "- Mostra nome e telefone (quando existente).",
   "- O grupo de Balcão facilita reutilizar atendimentos anteriores sem formalizar ainda o cadastro completo.",
   "",
   "##### Criação Rápida de Cliente de Balcão:",
   "- No final dos resultados aparece a opção ➕ 'Adicionar \"Nome digitado\" como Cliente de Balcão'.",
   "- Um clique cria e já seleciona o cliente para concluir o agendamento sem sair do modal.",
   "- Telefone pode ser adicionado depois (na edição) — fluxo mais rápido no atendimento presencial.",
   "",
   "##### Promoção Automática para Cliente Cadastrado:",
   "- Ao editar um cliente de Balcão e preencher um telefone válido (se antes estava vazio ou placeholder) o sistema converte automaticamente para cliente normal.",
   "- A flag interna isWalkIn passa de true para false sem ação extra.",
   "- Benefício: mantém histórico mesmo que o primeiro atendimento tenha sido rápido.",
   "",
   "##### Boas Práticas:",
   "- Use Balcão quando a fila está grande e não quer travar o fluxo.",
   "- Promova clientes que retornam frequentemente adicionando telefone/e-mail para habilitar automações e campanhas.",
   "- Evite criar clientes duplicados sempre reutilizando entradas de Balcão existentes na busca inteligente.",
   "",
   "### 3.4 WhatsApp - Automações Inteligentes",
   "",
   "O sistema de WhatsApp é um dos grandes diferenciais do TymerBook, reduzindo drasticamente as faltas e melhorando a comunicação com clientes.",
   "",
   "#### 3.4.1 Conexão do WhatsApp",
   "",
   "**Passo a Passo para Conectar:**",
   "",
   "1. **Acessar Configurações**: Vá em Dashboard > WhatsApp",
   "2. **Clicar em \"Conectar\"**: Botão para iniciar o processo",
   "3. **Escanear QR Code**: Use a câmera do WhatsApp Business do seu celular",
   "4. **Confirmação**: Sistema confirmará a conexão em alguns segundos",
   "",
   "**Requisitos:**",
   "- WhatsApp Business instalado no seu celular",
   "- Número do estabelecimento (não pode ser número pessoal)",
   "- Conexão estável com internet",
   "",
   "#### 3.4.2 Automações Disponíveis",
   "",
   "**Confirmação de Agendamento:**",
   "- **Quando**: Enviado imediatamente após cliente agendar",
   "- **Conteúdo**: Detalhes do agendamento (data, hora, serviço, profissional, valor)",
   "- **Objetivo**: Confirmar que o agendamento foi recebido",
   "",
   "**Notificação para o Profissional (NOVO):**",
   "- **Quando**: Enviado imediatamente após um novo agendamento ser criado na página pública",
   "- **Quem recebe**: O profissional selecionado no agendamento",
   "- **De onde sai**: Do número oficial da TymerBook conectado no sistema",
   "- **Conteúdo**: Nome do cliente, serviços, data, hora e valor total",
   "- **Observação**: Recurso padrão, sempre ativo (sem opção de desativar)",
   "- **Pré‑requisito**: O campo 'Telefone (WhatsApp)' do profissional precisa estar preenchido corretamente",
   "",
   "**Lembrete 24 horas:**",
   "- **Quando**: 24 horas antes do agendamento",
   "- **Conteúdo**: Lembrete amigável com detalhes do agendamento",
   "- **Objetivo**: Reduzir faltas e dar tempo para reagendamento se necessário",
   "",
   "**Lembrete 12 horas:**",
   "- **Quando**: 12 horas antes do agendamento",
   "- **Conteúdo**: Lembrete mais próximo com orientações",
   "- **Objetivo**: Garantir que o cliente não esqueça",
   "",
   "**Lembrete 2 horas:**",
   "- **Quando**: 2 horas antes do agendamento",
   "- **Conteúdo**: Lembrete final com orientação para chegar 10 min antes",
   "- **Objetivo**: Confirmação final e pontualidade",
   "",
   "**Lembrete 1 hora & 30 minutos (se habilitados):**",
   "- **Quando**: 60 ou 30 minutos antes",
   "- **Objetivo**: Reforço final em agendas críticas de alta rotatividade",
   "",
   "#### 3.4.2.1 E-mail Automático Pós-Agendamento",
   "O sistema envia (quando configurado globalmente) um e-mail de confirmação após um novo agendamento ser criado. Este e-mail contém:",
   "- Nome do cliente",
   "- Data e horário",
   "- Profissional e serviços",
   "- Valor total estimado",
   "- Instruções básicas ou políticas (quando definidas futuramente)",
   "",
   "",
   "#### 3.4.2.2 Mensagem Pós-Conclusão (Pesquisa de Satisfação / Agradecimento)",
   "Após um agendamento ser marcado como CONCLUÍDO, o sistema pode (se ativado) enviar uma mensagem de ‘pós-atendimento’ no WhatsApp. Essa mensagem pode ter dois objetivos principais:",
   "1. Solicitar avaliação (Google / satisfação)",
   "2. Apenas agradecer a visita e reforçar relacionamento",
   "",
   "Você controla:",
   "- Ativar / Desativar a automação",
   "- Atraso em minutos após a conclusão (ex.: 15, 30, 45, 60, 90)",
   "- Template da mensagem",
   "- Link de avaliação do Google (opcional)",
   "",
   "Se você não preencher o link do Google, ainda assim a mensagem pode ser usada como agradecimento ou para convidar o cliente a voltar em breve.",
   "",
   "##### Placeholders Disponíveis",
   "Você pode personalizar o texto com variáveis dinâmicas:",
   "- {nomeCliente} → Nome do cliente",
   "- {nomeBarbearia} → Nome configurado do estabelecimento",
   "- {linkAvaliacao} → Link do Google se configurado; caso contrário ficará vazio",
   "",
   "##### Boas Práticas de Mensagem",
   "Exemplos de templates:",
   "",
   "Mensagem de avaliação:",
   "\"Olá {nomeCliente}! Obrigado por escolher a {nomeBarbearia}. Poderia deixar sua avaliação? {linkAvaliacao}\"",
   "",
   "Mensagem apenas de agradecimento:",
   "\"{nomeCliente}, foi um prazer atender você hoje na {nomeBarbearia}! Qualquer coisa estamos à disposição. Até a próxima!\"",
   "",
   "Mensagem de fidelização sem link:",
   "\"Valeu pela visita, {nomeCliente}! Em breve traremos novidades para clientes VIP. Fique ligado!\"",
   "",
   "##### Quando Usar Sem o Link do Google?",
   "Se sua barbearia ainda não tem o perfil Google otimizado ou quer primeiro criar hábito de retorno, use mensagens de agradecimento sem link. Depois você pode ativar o link e começar a construir reputação pública.",
   "",
   "##### Como Ativar / Configurar",
   "1. Vá em Dashboard > WhatsApp",
   "2. Localize a seção ‘Pesquisa de Satisfação (Pós-atendimento)’",
   "3. Ative o switch ‘Enviar mensagem de avaliação’",
   "4. (Opcional) Cole o link de avaliação do Google",
   "5. Ajuste o atraso (minutos)",
   "6. Edite o template (use os placeholders)",
   "7. Salve as configurações",
   "8. Marque um agendamento como ‘Concluído’ para validar (mensagem será enviada após o atraso)",
   "",
   "##### Diferenciando Entre Lembretes e Pós-Atendimento",
   "| Tipo | Momento | Finalidade |",
   "| ---- | ------- | ---------- |",
   "| Confirmação | Após criar | Garantir registro do agendamento |",
   "| Lembretes (24h / 12h / 2h / 1h / 30min) | Antes do horário | Reduzir faltas |",
   "| Pós-atendimento | Depois de concluir | Agradecer / Coletar avaliação |",
   "",
   "---",
   "",
   "#### 3.4.3 Configuração das Automações",
   "",
   "**Para Ativar/Desativar Automações:**",
   "1. Acesse Dashboard > WhatsApp",
   "2. Localize a seção \"Configurações de Automação\"",
   "3. Use os interruptores para ativar/desativar cada tipo de mensagem",
   "4. As alterações são salvas automaticamente",
   "",
   "**Testar Mensagem:**",
   "- **Ferramenta de Teste**: Envie uma mensagem de teste para qualquer número",
   "- **Templates Prontos**: Modelos de confirmação e lembretes para testar",
   "- **Verificação**: Confirme se a integração está funcionando corretamente",
   "",
   "#### 3.4.4 Mensagens de Reativação",
   "",
   "**Para Clientes Inativos:**",
   "- Acesse Dashboard > Clientes Inativos",
   "- Selecione os clientes desejados",
   "- Escolha um template de promoção",
   "- Envie mensagens personalizadas em massa",
   "",
   "### 3.5 Configurações - Personalizando sua Barbearia",
   "",
   "#### 3.5.1 Profissionais",
   "",
   "**Cadastrar Equipe:**",
   "- **Nome Completo**: Identificação do profissional",
   "- **E-mail**: Para notificações (opcional)",
   "- **Telefone (WhatsApp)**: Contato direto — obrigatório para receber as notificações de novos agendamentos",
   "- **Especialidade**: Ex: Corte masculino, Barba, Sobrancelha",
   "- **Upload de Foto**: Avatar para identificação visual",
   "- **Regras de Comissão (Assinatura)**: Defina como calcular a comissão do colaborador quando o atendimento for coberto por uma assinatura do cliente:",
   "  - Tipo: Percentual (%) ou Fixo (R$)",
   "  - Valor: se Percentual, informe de 0 a 100; se Fixo, informe o valor em reais",
   "  - Esta regra só se aplica a atendimentos cobertos por Assinaturas. Para Pacotes/normal, vale a comissão padrão (%)",
   "",
   "**Sistema de Horários Individuais:**",
   "",
   "**Dias de Trabalho:**",
   "- Configure quais dias da semana cada profissional trabalha",
   "- Flexibilidade total para escalas diferentes",
   "",
   "**Horários de Início/Fim:**",
   "- Defina horário de entrada e saída para cada dia",
   "- Permite horários diferentes para cada dia da semana",
   "",
   "**Intervalos Recorrentes:**",
   "- Configure intervalos fixos (ex: almoço das 12h às 13h)",
   "- Automaticamente bloqueados na agenda",
   "",
   "**Exceções Pontuais:**",
   "- Bloqueie dias específicos (férias, folgas, compromissos)",
   "- Horários especiais para datas específicas",
   "- Fácil gestão de ausências",
   "",
      "#### 3.5.4 Intervalo de Horários da Agenda (Pública e Interna)",
      "",
      "Esta configuração permite definir a granularidade (em minutos) dos horários exibidos tanto na página pública de agendamentos quanto na agenda interna utilizada pela equipe.",
      "",
      "**Onde Ajustar:**",
      "- Acesse **Configurações > Estabelecimento**",
      "- Localize o campo **'Intervalo de Horários da Agenda (Pública e Interna)'**",
      "- Selecione um dos valores disponíveis (5, 10, 15, 20, 25, 30, 45 ou 60 minutos)",
      "",
      "**O Que Muda ao Alterar:**",
      "- ✅ Geração dos slots de horário disponíveis",
      "- ✅ Verificação de conflitos entre agendamentos",
      "- ✅ Cálculo da Taxa de Ocupação (usa o novo total de slots do dia)",
      "- ✅ Disponibilidade exibida para o cliente na página pública",
      "",
      "**Exemplos Práticos:**",
      "- Intervalo 5 min: Máxima flexibilidade, mais slots (recomendado para serviços muito curtos).",
      "- Intervalo 15 min: Equilíbrio entre precisão e simplicidade (recomendado para a maioria das barbearias).",
      "- Intervalo 30 min ou 60 min: Agendas com serviços longos e pouco fracionados.",
      "",
      "**Impacto na Taxa de Ocupação:**",
      "A taxa passa a considerar o novo número total de slots disponíveis no dia. Aumentar o intervalo tende a elevar a taxa (menos slots totais); reduzir o intervalo tende a diminuir (mais slots possíveis).",
      "",
      "**Boas Práticas:**",
      "- Ajuste antes de abrir a agenda ao público para evitar mudanças bruscas.",
      "- Se mudar depois, comunique a equipe (visão interna mudará imediatamente).",
      "- Para serviços de múltiplas durações, escolha um divisor comum (ex.: se tem serviços de 30 e 45 min, usar 15).",
      "",
      "**Perguntas Frequentes:**",
      "- *Mudar o intervalo cancela agendamentos existentes?* → Não. Eles permanecem inalterados.",
      "- *Posso alterar várias vezes no mesmo dia?* → Sim, mas evite para não confundir a equipe.",
      "- *Clientes verão horários mais 'limpos'?* → Sim, com intervalos maiores a visualização fica mais simples.",
      "",
   "##### Gestão de Acesso e Papéis",
   "Agora o proprietário pode definir o tipo de acesso de cada membro da equipe diretamente na tela de **Configurações > Profissionais** usando a opção 'Gerir Acesso'.",
   "",
   "**Papéis Disponíveis:**",
   "- **Dono**: Acesso administrativo completo (equivalente ao proprietário). Deve ser usado com cautela.",
   "- **Colaborador**: Acesso restrito apenas aos dados e métricas relacionados ao próprio profissional.",
   "",
   "**Como Alterar o Papel:**",
   "1. Vá em **Configurações > Profissionais**",
   "2. Clique no botão **Acesso** do profissional desejado",
   "3. No modal *Gerir Acesso*, selecione o papel (Dono ou Colaborador)",
   "4. Opcionalmente ajuste e-mail e senha (senha: mínimo 6 caracteres)",
   "5. Salve as alterações",
   "",
   "**Exibição no Sistema:**",
   "- O painel lateral agora mostra o e-mail do usuário logado e um badge indicando *Dono* ou *Colaborador*.",
   "- Na listagem de profissionais, cada item exibe também um badge com o papel atual.",
   "",
   "**Segurança Importante:**",
   "- Somente o proprietário (OWNER raiz) pode alterar papéis e credenciais de outros profissionais.",
   "- Promover um colaborador a Dono NÃO concede automaticamente permissão para reatribuir papéis de terceiros.",
   "- Use a promoção para Dono apenas quando realmente precisar delegar administração completa.",
   "",
   "**Boas Práticas:**",
   "- Mantenha a maioria dos usuários como Colaboradores para reduzir riscos.",
   "- Revise periodicamente quem está como Dono.",
   "- Altere senhas de acesso de colaboradores desligados imediatamente.",
   "",
   "#### 3.5.2 Serviços",
   "",
   "**Cadastro Completo:**",
   "- **Nome do Serviço**: Ex: Corte Masculino, Barba, Sobrancelha",
   "- **Descrição**: Detalhes do que está incluído",
   "- **Preço**: Valor em reais",
   "- **Duração**: Tempo necessário em minutos",
   "- **Upload de Imagem**: Foto representativa do serviço",
   "",
   "**Gestão de Preços:**",
   "- Atualização fácil de valores",
   "- Histórico de alterações",
   "- Diferentes preços por profissional (se necessário)",
   "",
   "#### 3.5.3 Promoções",
   "",
   "**Templates de Mensagem:**",
   "- **Modelos Prontos**: Para diferentes tipos de promoção",
   "- **Personalização**: Adapte as mensagens à sua marca",
   "- **Variáveis Dinâmicas**: Nome do cliente, link de agendamento automático",
   "",
   "**Exemplos de Templates:**",
   "- Desconto de aniversário",
   "- Promoção de retorno",
   "- Ofertas sazonais",
   "- Pacotes especiais",
   "",
   "### 3.6 Relatórios & Financeiro (Novidades)",
   "",
   "Esta funcionalidade é o centro de inteligência operacional e financeira. Aqui você:",
   "- Acompanha faturamento, agendamentos concluídos, ticket médio e taxa de conversão por qualquer intervalo.",
   "- Visualiza gráficos diários e mensais para identificar picos e sazonalidade.",
   "- Navega entre meses rapidamente (últimos 12 meses).",
   "- Enxerga a distribuição por métodos de pagamento (Dinheiro, Pix, Cartão e Pré‑pago).",
   "- Consulta transações recentes e serviços mais vendidos (quando habilitados).",
   "- Gerencia custos fixos e obtém o lucro líquido estimado do mês.",
   "",
   "#### 3.6.0 Formas de Pagamento (inclui Pré‑pago)",
   "- **Pré‑pago** representa atendimentos quitados com créditos de pacotes/assinaturas do cliente.",
   "- Como registrar: ao concluir o atendimento, clique no botão **Pré‑pago** no modal de pagamento para consumir créditos válidos do cliente.",
   "- Distribuição e ordem padrão dos métodos: Dinheiro → Pix → Cartão → Pré‑pago.",
   "- Relatórios e gráficos exibem o total por método, incluindo **Pré‑pago**.",
   "",
   "#### 3.6.1 Novo Calendário de Período",
   "- Agora você pode escolher qualquer intervalo de datas e todos os cards principais refletem exatamente esse período.",
   "- Se selecionar apenas 1 dia, o sistema expande automaticamente para mostrar o MÊS inteiro desse dia nas análises e gráficos (modo mensal rápido).",
   "- Navegação mensal com botões (◀ ▶) na Análise Mensal para avançar/voltar dentro dos últimos 12 meses.",
   "- Os títulos dos cards indicam 'no período' para evitar confusão entre dia, intervalo e mês.",
   "",
   "#### 3.6.2 Custos Mensais (Nova Seção)",
   "- Localizada no final da página de Relatórios & Financeiro, imediatamente acima da seção 'Análise de Lucratividade do Período'.",
   "- Suporte a dois tipos de custos: Recorrente e Somente este mês (compras pontuais).",
   "- Recorrentes aparecem em todos os meses; 'Somente este mês' ficam vinculados ao mês/ano atual na criação.",
   "- Campos: Nome, Valor (R$), Tipo (select), Remover.",
   "- Valores normalizados: vírgula aceita como decimal e negativos convertidos para 0.",
   "- Limite de 2 casas decimais aplicado automaticamente.",
   "- Auditoria interna: cada item registra criação e última alteração (para futuro histórico).",
   "- Botão 'Adicionar' cria um item Recorrente por padrão (pode mudar depois).",
   "- Botão 'Salvar alterações' persiste a lista completa no sistema.",
   "- Total mensal inclui Recorrentes + Itens 'Somente este mês' do mês selecionado.",
   "- Não há cards nesta seção. O **Total mensal de custos** aparece logo abaixo do botão 'Salvar alterações'.",
   "- Navegação de mês (◀ ▶) compartilha lógica da Análise Mensal.",
   "- Indicadores de variação removidos (evita interpretação errada sem comparação histórica).",
   "- Boas práticas: registrar gastos pontuais como 'Somente este mês'; ao tornarem-se recorrentes, mudar o tipo.",
   "",
   "- Integração com a Análise de Lucratividade: quando não houver despesas lançadas no Caixa no período, o card 'Custos Mensais' utilizará automaticamente os custos configurados aqui como fallback visual (para não exibir zero).",
   "- Impacto no Lucro Líquido: o valor mostrado de Lucro Líquido no dashboard é recalculado considerando esse fallback. Já os dados analíticos (API) continuam em regime de caixa; o fallback afeta somente a exibição.",
   "",
   "> 💡 Dica: Use o Lucro Líquido estimado para decidir ajustes de preço e promoções.",
   "",
   "#### 3.6.3 Análise de Lucratividade do Período",
   "Esta seção resume o resultado do NEGÓCIO no intervalo selecionado, agora com modelo HÍBRIDO (Caixa + Operação).",
   "",
   "- **Fontes de dados:**",
   "  - Operação: apenas agendamentos CONCLUÍDOS do período (bruto, descontos e comissões).",
   "  - Caixa: registros financeiros do período para DESPESAS e para RECEITAS de vendas de planos (pacotes/assinaturas).",
   "- **Fórmula‑mãe:**",
   "  - Receita Líquida = Receita Bruta (Operação) + Receita de Vendas de Planos (Caixa) − Descontos (Operação)",
   "  - Lucro Líquido = Receita Líquida − Comissões (Operação) − Custos Mensais (Caixa; com fallback de Configurações se vazio)",
   "- **Custos:**",
   "  - Por padrão, usa DESPESAS registradas no Caixa no período.",
   "  - Se não houver despesas no período, o card usa os custos configurados em 'Custos Mensais' (integrais por mês do intervalo) como fallback visual.",
   "- **Ícone de ajuda (Receita Líquida):** clique no ícone ao lado do título para ver um resumo das fontes e da fórmula; funciona no celular e permanece aberto até você fechar.",
   "- **Colaboradores:** na visão de colaborador, os valores consideram ganhos (comissões) do profissional; o Lucro Líquido exibido corresponde aos seus ganhos no período.",
   "- **Posicionamento:** aparece logo abaixo da seção 'Custos Mensais'.",
   "",
   "Cards nesta seção:",
   "- Receita Bruta (Operação) no período",
   "- Receita de Vendas de Planos (Caixa) no período",
   "- Receita Líquida (com ajuda por clique)",
   "- Comissões (Operação) no período",
   "- Custos Mensais (Caixa; com fallback quando necessário)",
   "- Lucro Líquido do período",
   "",
   "#### 3.6.4 Pré‑pago (Pacotes/Assinaturas) — Cards do Período",
   "- Valor coberto por Pré‑pago: soma dos atendimentos concluídos pagos com Pacote/Assinatura (indica quanto da operação foi coberto por créditos).",
   "- Atendimentos Pré‑pagos: quantidade de atendimentos concluídos com cobertura de Pacote/Assinatura.",
   "- Descontos no período: soma dos descontos aplicados em atendimentos concluídos (independe do método de pagamento).",
   "- Observações:",
   "  - Atendimentos Pré‑pagos fazem parte da Receita Bruta (Operação).",
   "  - Vendas de Planos recebidas em caixa entram em 'Receita de Vendas de Planos' na lucratividade.",
   "  - Comissões continuam sendo calculadas normalmente para atendimentos Pré‑pagos.",
   "",
   "---",
   "",
   "### 3.7 Sistema de Comissões (Profissionais e Colaboradores)",
   "",
   "O TymerBook possui um sistema de comissões integrado para dar transparência aos ganhos dos colaboradores e manter a consistência dos relatórios.",
   "",
   "#### Onde configurar a comissão (%)",
   "- Acesse **Configurações > Profissionais**",
   "- No cadastro/edição do profissional, informe **Comissão (%)**",
   "- Intervalo recomendado: 0% a 100% (ex.: 50 = 50%)",
   "- Este percentual será usado para calcular a comissão prevista e a comissão final no momento da conclusão do atendimento",
   "",
   "#### Como a comissão é calculada",
   "- **Prevista (agendamentos não concluídos):** `comissão prevista = percentual do profissional × valor bruto do agendamento`",
   "- **Final (snapshot ao concluir):** ao marcar o agendamento como **Concluído**, o sistema grava um **snapshot** do valor da comissão no próprio agendamento. Esse valor fica fixo historicamente e é usado nos relatórios",
   "- Se o percentual do profissional for alterado depois, a **prevista** passará a refletir o novo percentual; a **final** já salva (snapshot) não muda",

   "#### Comissão em atendimentos cobertos por Assinatura",
   "Quando um atendimento estiver (ou puder estar) coberto por uma Assinatura do cliente, você pode aplicar regras de comissão específicas por profissional:",
   "- Onde configurar: **Configurações > Profissionais > Regras de Comissão (Assinatura)**",
   "- Opções disponíveis:",
   "  - Tipo = Percentual (%): o valor informado (0–100) é aplicado sobre o bruto do atendimento",
   "  - Tipo = Fixo (R$): o valor informado é a comissão direta (independe do valor do serviço)",
   "- Como aparece na Agenda:",
   "  - Se o agendamento NÃO estiver concluído e exibir os badges 'Coberto por assinatura' ou 'Assinatura pode cobrir', a **Comissão (prevista)** já usa a regra de Assinatura",
   "  - Se NÃO houver cobertura por assinatura, a **Comissão (prevista)** usa o percentual padrão do profissional",
   "- Ao concluir o atendimento:",
   "  - Se a origem de pagamento (paymentSource) for Assinatura (Pré‑pago), o snapshot `commissionEarned` usa a regra de Assinatura",
   "  - Se a origem for Pacote (Pré‑pago) ou pagamento normal (Dinheiro/Pix/Cartão), a comissão final usa o percentual padrão do profissional",
   "- Relatórios: sempre usam o snapshot salvo em cada atendimento. Logo, atendimentos de Assinatura respeitam a regra de Assinatura; Pacotes e demais métodos usam o percentual padrão",
   "- Exemplos:",
   "  - Serviço R$ 40, regra Assinatura = Fixo R$ 20 → Comissão prevista/final = R$ 20",
   "  - Serviço R$ 40, regra Assinatura = 50% → Comissão prevista/final = R$ 20",
   "- Observações:",
   "  - Se algum campo da regra de Assinatura estiver ausente, o sistema volta a usar o percentual padrão",
   "  - Regras de Assinatura não afetam Pacotes (créditos): para Pacotes, permanece a comissão padrão (%)",
   "",
   "#### Onde a comissão aparece",
   "- **Agenda**:",
   "  - Nos cartões dos agendamentos: mostra **Bruto** e **Comissão**",
   "  - Para não concluídos: aparece **Comissão (prevista)**",
   "  - Para concluídos: aparece **Comissão** (snapshot)",
   "  - No card do topo, colaboradores veem **Ganhos Hoje** (soma das comissões de hoje)",
   "",
   "- **Relatórios & Financeiro**:",
   "  - Para **Colaboradores**: os números e gráficos consideram **Ganhos (comissão)**",
   "    - Cards principais do período",
   "    - Gráfico de **Ganhos Diários**",
   "    - **Análise Mensal**: 'Ganhos Totais' e 'Ticket Médio (Comissão)'",
   "    - **Transações Recentes**: exibe **Bruto** e **Comissão**",
   "    - **Meus Serviços Mais Rentáveis**: ganhos por serviço (comissão distribuída)",
   "    - **Análise de Horários**: valor considera ganhos",
   "  - Para **Donos**: a visão permanece em **Faturamento (bruto)**",
   "",
   "- **Relatório de Serviços**:",
   "  - Dono: receita bruta por serviço",
   "  - Colaborador: **ganhos por serviço** = comissão do atendimento **distribuída proporcionalmente** ao preço de cada serviço do atendimento (em caso de múltiplos serviços)",
   "",
   "#### Regras e observações importantes",
   "- **Cancelados** não entram em ganhos/receita",
   "- Em algumas análises, **Concluídos** (e eventualmente **Em andamento**) são considerados para totalizações",
   "- **Múltiplos serviços no mesmo atendimento:** a comissão é rateada entre os serviços **proporcionalmente ao preço** de cada um",
   "- **Transparência para o colaborador:** a comissão aparece claramente tanto nas telas da Agenda quanto no Financeiro",
   "- **Atendimentos pagos via Pré‑pago (pacotes/assinaturas):** a comissão é calculada normalmente sobre o(s) serviço(s) e registrada no snapshot ao concluir",
   "",
   "> Exemplo: Serviço de R$ 100 com comissão de 50% → Ganho do colaborador = R$ 50,00",
   "",
   "---",
   "",
   "### 3.8 Pacotes e Assinaturas de Clientes",
   "",
   "Funcionalidade para fidelização e previsibilidade de receita: você pode vender **Pacotes** (créditos) ou **Assinaturas** (recorrentes) aos seus clientes e registrar o consumo diretamente no atendimento.",
   "",
   "#### 3.8.1 Pacotes (Créditos)",
   "- Venda um pacote com quantidade de sessões e/ou créditos vinculados a um cliente.",
   "- Configure nome, descrição, valor e validade (opcional).",
   "- O saldo é consumido automaticamente quando o atendimento é lançado como **Pré‑pago**.",
   "- Acompanhe o saldo restante na ficha do cliente.",
   "",
   "#### 3.8.2 Assinaturas (Recorrentes)",
   "- Defina uma assinatura com renovação por ciclo (ex.: mensal) e benefícios (ex.: X serviços inclusos).",
   "- No início de cada ciclo, os créditos da assinatura são renovados automaticamente no sistema.",
   "- A cobrança ao cliente deve seguir o seu processo de recebimento (dinheiro/pix/cartão); o TymerBook registra o consumo e o saldo.",
   "",
   "#### 3.8.3 Como Registrar e Consumir",
   "1. Cadastre um Pacote ou Assinatura na ficha do cliente.",
   "2. Ao concluir um atendimento, no modal de pagamento clique no botão **Pré‑pago**.",
   "3. O sistema consumirá créditos válidos (de pacote ou assinatura) e registrará a transação como **Pré‑pago**.",
   "4. Se não houver saldo, escolha outra forma de pagamento (Dinheiro, Pix, Cartão).",
   "",
   "#### 3.8.4 Impacto nos Relatórios",
   "- Atendimentos **Pré‑pago** entram na **Receita Bruta (Operação)** do período e aparecem na distribuição por métodos.",
   "- Vendas de Planos (Pacotes/Assinaturas) registradas no **Caixa** entram como **Receita de Vendas de Planos** na Análise de Lucratividade.",
   "- A 'Análise de Lucratividade do Período' usa modelo **Híbrido (Caixa + Operação)**:",
   "  - Receita Líquida = Receita Bruta (Operação) + Receita de Vendas de Planos (Caixa) − Descontos (Operação)",
   "  - Lucro Líquido = Receita Líquida − Comissões (Operação) − Custos Mensais (Caixa; com fallback de Configurações se vazio)",
   "- **Custos Mensais**: por padrão, são as DESPESAS do Caixa no período; se não houver, o card usa os custos configurados em 'Custos Mensais' como fallback visual (integrais por mês do intervalo).",
   "- **Comissões**: calculadas e registradas ao concluir (snapshot), inclusive para Pré‑pago; entram como abatimento na fórmula de lucro.",
   "- Ícone de ajuda ao lado de 'Receita Líquida': toque/clique para abrir uma explicação resumida da fórmula e das fontes; permanece aberto até fechar.",
   "",
   "#### 3.8.5 Boas Práticas",
   "- Defina validade para pacotes para incentivar uso dentro do período.",
   "- Descreva claramente o que cada pacote/assinatura inclui.",
   "- Treine a equipe para selecionar **Pré‑pago** quando o cliente tiver créditos.",
   "- Revise saldos de clientes periodicamente para oferecer renovações.",
   "",
   "#### 3.8.6 Gestão: Cancelar/Desativar/Renovar",
   "",
   "As ações abaixo ficam disponíveis na ficha do cliente (modais de **Assinatura** e **Pacote**). Elas são registradas financeiramente e atualizam o histórico do cliente na hora.",
   "",
   "**Permissão:** Somente o **Dono** pode executar estas ações.",
   "",
   "**Assinatura — Cancelar (com estorno opcional):**",
   "1. Acesse Clientes > selecione o cliente > Assinatura.",
   "2. Na assinatura ativa, clique em **Cancelar**.",
   "3. Confirme no alerta e, se necessário, informe um **Valor de estorno (opcional)**.",
   "4. Resultado: a assinatura fica **Cancelada** imediatamente.",
   "   - Financeiro: cria uma **Despesa** (categoria: Assinaturas) referente ao estorno.",
   "   - Cobertura: agendamentos já cobertos permanecem com o badge (registro histórico).",
   "",
   "**Assinatura — Renovar (preço opcional):**",
   "1. Na mesma lista, clique em **Renovar**.",
   "2. No alerta, deixe o **Preço (opcional)** em branco para usar o preço do plano ou informe um valor personalizado.",
   "3. Confirme.",
   "4. Resultado: cria um novo ciclo de assinatura a partir de agora.",
   "   - Financeiro: cria uma **Receita** (categoria: Assinaturas).",
   "",
   "**Pacote — Desativar (com estorno opcional):**",
   "1. Acesse Clientes > selecione o cliente > Pacote.",
   "2. No pacote **Ativo**, clique em **Desativar**.",
   "3. Confirme no alerta e, se necessário, informe um **Valor de estorno (opcional)**.",
   "4. Resultado: o pacote é **expirado imediatamente** (saldo deixa de valer).",
   "   - Financeiro: cria uma **Despesa** (categoria: Estornos de Pacotes).",
   "",
   "**Pacote — Renovar (preço opcional):**",
   "1. Na mesma lista, clique em **Renovar**.",
   "2. No alerta, deixe o **Preço (opcional)** em branco para usar o preço do pacote ou informe um valor personalizado.",
   "3. Confirme.",
   "4. Resultado: registra uma nova venda de pacote para o cliente (novo saldo/validade).",
   "   - Financeiro: cria uma **Receita** (categoria: Pacotes de Serviços).",
   "",
   "> Observações:",
   "- O histórico do cliente exibe chips de status (Ativo, Expirado, Cancelada).",
   "- As ações exibem alertas de confirmação com campos de **Preço/Estorno** quando aplicável.",
   "- Se não informar preço na renovação, o sistema usa o preço cadastrado do plano/pacote.",
   "- Agendamentos cobertos no passado continuam marcados (registro histórico de cobertura).",
   "",
   "## 4. Sua Página Pública de Agendamento",
   "",
   "### 4.1 Como Funciona para o Cliente Final",
   "",
   "Seu link personalizado (`tymerbook.com/agendamento/[seu-link]`) oferece uma experiência completa de agendamento:",
   "",
   "#### Fluxo do Cliente:",
   "",
   "**Etapa 1 - Escolher Serviço:**",
   "- Lista visual de todos os serviços disponíveis",
   "- Preços e durações claramente exibidos",
   "- Imagens dos serviços (se cadastradas)",
   "- Opção de adicionar serviços complementares",
   "",
   "**Etapa 2 - Selecionar Profissional:**",
   "- Fotos e especialidades dos profissionais",
   "- Opção \"Qualquer profissional\" disponível",
   "- Horários específicos de cada um",
   "",
   "**Etapa 3 - Escolher Data:**",
   "- Calendário interativo",
   "- Apenas datas disponíveis aparecem",
   "- Bloqueios automáticos de feriados/folgas",
   "",
   "**Etapa 4 - Selecionar Horário:**",
   "- Grade de horários disponíveis",
   "- Atualização em tempo real",
   "- Duração total calculada automaticamente",
   "",
   "**Etapa 5 - Dados do Cliente:**",
   "- Formulário simples e intuitivo",
   "- Campos: Nome, telefone, e-mail",
   "- Data de nascimento (opcional)",
   "- Observações (opcional)",
   "",
   "**Etapa 6 - Confirmação:**",
   "- Resumo completo do agendamento",
   "- Valor total e forma de pagamento",
   "- Confirmação via WhatsApp automática",
   "",
   "### 4.2 QR Code para Impressão",
   "",
   "#### Gerar QR Code:",
   "1. **Acesso**: Configurações > Estabelecimento",
   "2. **Localizar**: Seção \"Link Público do Agendamento\"",
   "3. **Clicar**: \"Gerar QR Code para Impressão\"",
   "",
   "#### Funcionalidades do QR Code:",
   "- **Preview do Cartaz**: Visualize antes de imprimir",
   "- **Logo Personalizado**: Sua marca no cartaz",
   "- **Download em PDF**: Arquivo pronto para impressão",
   "- **Tamanho Otimizado**: Ideal para colar no estabelecimento",
   "",
   "#### Como Usar:",
   "- Imprima o PDF gerado",
   "- Cole em local visível na barbearia (balcão, parede, espelho)",
   "- Clientes escaneiam com a câmera do celular",
   "- Redirecionamento automático para sua página de agendamento",
   "- Facilita o agendamento dos clientes que aparecem no estabelecimento sem horário agendado",
   "- Melhora na gestão, pois previne esquecimento de agendamentos pelo profissional",
   "",
   "---",
   "",
   "## 5. Gerenciamento da Sua Assinatura",
   "",
   "### 5.1 Página de Assinatura",
   "",
   "Acesse **Dashboard > Minha Assinatura** para visualizar:",
   "",
   "> Observação importante: esta é a assinatura do SOFTWARE TymerBook (sua licença de uso).",
   "> Para as assinaturas que você vende aos seus clientes, consulte **Seção 3.8 – Pacotes e Assinaturas de Clientes**.",
   "",
   "#### Informações da Conta:",
   "- **Plano Atual**: Básico, Premium ou Ultra",
   "- **Status**: Ativa, Atrasada ou Cancelada",
   "- **Data de Renovação**: Próximo vencimento",
   "- **Ciclo de Pagamento**: Mensal ou Anual",
   "",
   "#### Recursos Inclusos:",
   "**Básico:**",
   "- Até 1 profissional",
   "- Clientes ilimitados",
   "- Agendamentos ilimitados",
   "- Serviços ilimitados",
   "- Integração WhatsApp",
   "",
   "**Premium:**",
   "- Até 3 profissionais",
   "- Todos os recursos do Básico",
   "- Relatórios avançados",
   "",
   "**Ultra:**",
   "- Profissionais ilimitados",
   "- Todos os recursos do Premium",
   "- Suporte prioritário",
   "",
   "### 5.2 Limites de Plano",
   "",
   "#### Sistema de Controle:",
   "- **Contagem Automática**: Sistema monitora uso em tempo real",
   "- **Alertas Visuais**: Notificação quando próximo do limite",
   "- **Bloqueio Preventivo**: Impede criação além do limite",
   "- **Sugestões de Upgrade**: Orientações para expandir",
   "",
   "#### Para Profissionais:",
   "- **Básico**: Máximo 1 profissional ativo",
   "- **Premium**: Máximo 3 profissionais ativos",
   "- **Ultra**: Ilimitado",
   "",
   "### 5.3 Portal da Kirvano",
   "",
   "#### Gerenciar Assinatura:",
   "1. **Clicar**: \"Gerenciar Assinatura\" na página de assinatura",
   "2. **Redirecionamento**: Portal seguro da Kirvano",
   "3. **Funcionalidades Disponíveis**:",
   "   - Atualizar cartão de crédito",
   "   - Alterar dados de cobrança",
   "   - Cancelar assinatura",
   "   - Histórico de pagamentos",
   "   - Alterar plano",
   "",
   "#### Segurança:",
   "- Portal criptografado e seguro",
   "- Dados de pagamento protegidos",
   "- Retorno automático ao TymerBook",
   "- Notificações por e-mail",
   "",
   "---",
   "",
   "## 6. Disponibilidade e Suporte",
   "",
   "### 6.1 Infraestrutura de Alta Performance",
   "",
   "#### Disponibilidade 24/7:",
   "- **Servidor VPS Dedicado**: Hospedagem em servidor de alta performance",
   "- **Uptime 99.9%**: Sistema disponível 24 horas por dia, 7 dias por semana",
   "- **Monitoramento Contínuo**: Equipe técnica monitora o sistema constantemente",
   "- **Redundância**: Múltiplos pontos de acesso para garantir disponibilidade",
   "",
   "#### Segurança dos Dados:",
   "- **Backups Automáticos**: Realizados diariamente",
   "- **Criptografia**: Dados protegidos com tecnologia SSL",
   "- **Conformidade LGPD**: Tratamento seguro de dados pessoais",
   "- **Armazenamento Seguro**: Dados em ambiente protegido",
   "",
   "### 6.2 Suporte Técnico",
   "",
   "#### Como Obter Ajuda:",
   "",
   "**Através do Sistema:**",
   "1. Acesse Dashboard > Minha Assinatura",
   "2. Clique em \"Contatar Suporte\"",
   "3. Será redirecionado diretamente para o WhatsApp, onde receberá o devido suporte",
   "4. Nossa equipe responderá o mais rápido possível",
   "",
   "**Tipos de Suporte:**",
   "- **Dúvidas sobre Funcionalidades**: Como usar recursos do sistema",
   "- **Problemas Técnicos**: Dificuldades de acesso ou erro no sistema",
   "- **Configuração Inicial**: Ajuda para primeiros passos",
   "- **Integração WhatsApp**: Suporte para conexão e automações",
   "- **Treinamento**: Orientações para aproveitar melhor o sistema",
   "",
   "#### Canais de Suporte:",
   "- **E-mail**: suporte@tymerbook.com",
   "- **WhatsApp**: Disponível na página de assinatura",
   "",
   "#### Suporte Prioritário (Plano Ultra):",
   "- **Resposta em até 2 horas**: Atendimento mais rápido",
   "- **Canal Direto**: Linha de contato exclusiva",
   "- **Suporte via Telefone**: Quando necessário",
   "- **Treinamento Personalizado**: Sessões individuais quando solicitado",
   "",
   "---",
   "",
   "## 7. Dicas para Maximizar Resultados",
   "",
   "### 7.1 Melhores Práticas",
   "",
   "#### Configure Corretamente:",
   "- ✅ Preencha todas as informações do estabelecimento",
   "- ✅ Cadastre todos os profissionais com fotos",
   "- ✅ Configure horários individuais detalhadamente",
   "- ✅ Adicione imagens aos serviços",
   "- ✅ Conecte o WhatsApp e ative todas as automações",
   "",
   "#### Use as Automações:",
   "- ✅ Mantenha lembretes ativos para reduzir faltas",
   "- ✅ Configure mensagens de reativação",
   "- ✅ Monitore estatísticas de entrega",
   "- ✅ Teste mensagens regularmente",
   "",
   "#### Promova Sua Página:",
   "- ✅ Imprima e cole o QR Code no estabelecimento",
   "- ✅ Compartilhe o link nas redes sociais",
   "- ✅ Inclua o link na assinatura do e-mail",
   "- ✅ Oriente clientes sobre o agendamento online",
   "",
   "### 7.2 Métricas Importantes",
   "",
   "#### Acompanhe Regularmente:",
   "- **Taxa de Ocupação**: Meta acima de 70%",
   "- **No-Show Rate**: Objetivo abaixo de 10%",
   "- **Clientes Inativos**: Reaproveite mensalmente",
   "- **Faturamento Diário**: Compare com períodos anteriores",
   "- **Efetividade WhatsApp**: Taxa de entrega acima de 95%",
   "",
   "#### Relatórios Mensais:",
   "- Analise crescimento de faturamento",
   "- Identifique profissionais mais produtivos",
   "- Verifique evolução da base de clientes",
   "- Acompanhe sazonalidade dos serviços",
   "",
   "---",
   "",
   "## 8. Solução de Problemas Comuns",
   "",
   "### 8.1 WhatsApp não Conecta",
   "",
   "**Possíveis Causas:**",
   "- QR Code expirado",
   "- WhatsApp Business não instalado",
   "- Problemas de conexão",
   "",
   "**Soluções:**",
   "1. Atualize a página e gere novo QR Code",
   "2. Certifique-se de usar WhatsApp Business",
   "3. Verifique conexão com internet",
   "",
   "### 8.2 Agendamentos não Aparecem",
   "",
   "**Verificações:**",
   "- Confirme data e filtros aplicados",
   "- Verifique se profissional está ativo",
   "- Confirme se agendamento não foi cancelado",
   "",
   "### 8.3 Clientes não Conseguem Agendar",
   "",
   "**Possíveis Problemas:**",
   "- Horários não configurados",
   "- Profissional sem agenda ativa",
   "- Serviços inativos",
   "- Link personalizado incorreto",
   "",
   "**Soluções:**",
   "- Revise configurações de horários",
   "- Ative agendas dos profissionais",
   "- Verifique status dos serviços",
   "- Confirme link nas configurações",
   "",
   "---",
   "",
   "## Conclusão",
   "",
   "O TymerBook foi desenvolvido especificamente para transformar a gestão do seu estabelecimento, automatizando processos, reduzindo faltas e aumentando o faturamento. Com este manual, você tem todas as informações necessárias para aproveitar ao máximo todas as funcionalidades.",
   "",
   "### Próximos Passos:",
   "1. ✅ Complete a configuração inicial",
   "2. ✅ Cadastre sua equipe e serviços",
   "3. ✅ Configure os horários",
   "4. ✅ Conecte o WhatsApp e ative automações",
   "5. ✅ Imprima e cole o QR Code",
   "6. ✅ Comece a agendar e acompanhar resultados",
   "",
   "**Lembre-se**: Nossa equipe de suporte está sempre disponível para ajudar você a ter sucesso com o TymerBook!",
   "",
   "---",
   "",
   "*Este manual é atualizado regularmente. Para dúvidas ou sugestões, entre em contato através do botão \"Contatar Suporte\" em sua conta.*",
   "",
   "TymerBook © 2025 – Foco em resultados para sua barbearia.",
].join("\n");